# Generated by Django 4.1.1 on 2022-09-24 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('e_mail', models.EmailField(max_length=50, verbose_name='EMail')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=50, verbose_name='Oximetra')),
                ('f_respiratoria', models.CharField(max_length=50, verbose_name='Frecuencia Respiratoria')),
                ('f_cardiaca', models.CharField(max_length=50, verbose_name='Frecuencia Cardiaca')),
                ('temperatura', models.CharField(max_length=50, verbose_name='Temperatura')),
                ('presion_arterial', models.CharField(max_length=50, verbose_name='Presion Arterial')),
                ('glicemias', models.CharField(max_length=50, verbose_name='Glicemias')),
                ('diagnosticos', models.CharField(max_length=8000, verbose_name='Diagnosticos')),
                ('cuidados', models.CharField(max_length=8000, verbose_name='Cuidados')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='backend_Hospital.enfermero')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='backend_Hospital.familiar')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='backend_Hospital.historia')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='backend_Hospital.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
