# Generated by Django 4.1.1 on 2022-09-28 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='medico',
            name='registro',
            field=models.CharField(default=None, max_length=50, verbose_name='Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_Hospital.enfermero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_Hospital.familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_Hospital.historia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_Hospital.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
