# Generated by Django 4.1.1 on 2022-09-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_Hospital', '0002_remove_usuario_contraseña_medico_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
    ]
